AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Ascode.nl IAM User Stack
Resources:
  echristiaans:
    Type: AWS::IAM::User
    Properties:
      Path: "/"
      LoginProfile:
        Password: myP@ssW0rd
      Policies:
      - PolicyName: giveaccesstoqueueonly
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:*
            Resource:
            - !GetAtt myqueue.Arn
          - Effect: Deny
            Action:
            - sqs:*
            NotResource:
            - !GetAtt myqueue.Arn
   myaccesskey:
     Type: AWS::IAM::AccessKey
     Properties:
       UserName: !Ref echristiaans
